# Generated by Django 3.2.18 on 2023-05-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_alter_transactionhistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='mode',
            field=models.CharField(choices=[('trans', 'Transfer'), ('req', 'Request')], default='trans', max_length=10),
            preserve_default=False,
        ),
    ]
