# Generated by Django 3.2.18 on 2023-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_transactionhistory_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(default='completed', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euros'), ('GBP', 'GB Pound')], max_length=3),
        ),
    ]
