# Generated by Django 4.2.4 on 2023-09-15 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_alter_emotionhistory_dated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionhistory",
            name="time_added",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
